name: Release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: 
      [closed]
jobs:
  build-and-deploy:
    name: Release
    # if: ${{ github.event.pull_request.merged }} //需要进行pr审核时开启
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install and Build
        run: |
          npm install -g yarn
          yarn
          npm run build

      - name: List files
        run: ls -la
        working-directory: ${{ github.workspace }}/dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ github.workspace }}/dist